###############
### GUITARS ###
###############

### GET ALL GUITARS:
GET http://localhost:3000/guitars

### GET ONE GUITAR:
GET http://localhost:3000/guitars/1

### CREATE A GUITAR:
POST http://localhost:3000/guitars
Content-Type: application/json

{
    "model": "Jazzmaster",
    "brandName": "Fender",
    "year": 1988,
    "description": "A beautiful guitar",
    "name":"Kurt Cobain"
}

### UPDATE A GUITAR MODEL:
PATCH http://localhost:3000/guitars/1
Content-Type: application/json

{
    "model": "Telecaster Deluxe"
}

###############
### BRANDS ####
###############

### GET ALL BRANDS:
GET http://localhost:3000/brands

### GET ONE BRAND:
GET http://localhost:3000/brands/1

### CREATE A BRAND:
POST http://localhost:3000/brands
Content-Type: application/json

{
    "name": "Boss",
    "code": "BOS"
}

### UPDATE A BRAND NAME:
PATCH http://localhost:3000/brands/1
Content-Type: application/json

{
    "name": "Headrush",
    "code": "HEA"
}

##############
### PEDALS ###
##############

### GET ALL PEDALS:
GET http://localhost:3000/pedals

### GET ONE PEDAL:
GET http://localhost:3000/pedals/2

### CREATE A PEDAL:
POST http://localhost:3000/pedals
Content-Type: application/json

{
    "model": "MX5",
    "description": "Multi-effects pedal",
    "brandName": "Headrush",
    "year": 2024
}

### UPDATE A PEDAL MODEL:
PATCH http://localhost:3000/pedals/654
Content-Type: application/json

{
    "model": "MX9"
}