###############
### GUITARS ###
###############

### GET ALL GUITARS:
GET http://localhost:3000/guitars

### GET ONE GUITAR:
GET http://localhost:3000/guitars/1

### CREATE A GUITAR:
POST http://localhost:3000/guitars
Content-Type: application/json

{
    "model": "GK Studio",
    "brandName": "Cordoba",
    "year": 2002,
    "name":"La Cordoba"
}

### UPDATE A GUITAR MODEL:
PATCH http://localhost:3000/guitars/1
Content-Type: application/json

{
    "model": "Telecaster Deluxe"
}

###############
### BRANDS ####
###############

### GET ALL BRANDS:
GET http://localhost:3000/brands

### CREATE A BRAND:
POST http://localhost:3000/brands
Content-Type: application/json

{
    "name": "Squier",
    "code": "SQU"
}

##############
### PEDALS ###
##############

### GET ALL PEDALS:
GET http://localhost:3000/pedals

### GET ONE PEDAL:
GET http://localhost:3000/pedals/1

### CREATE A PEDAL:
POST http://localhost:3000/pedals
Content-Type: application/json

{
    "model": "DS-1",
    "name": "Distortion",
    "brandName": "Boss",
    "year": 1978
}